//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace GPSWithFriends.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cs.uoregon.edu/", ConfigurationName="Server.GPSwfriends")]
    public interface GPSwfriends {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/authenticateRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/authenticateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult Beginauthenticate(GPSWithFriends.Server.authenticateRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.authenticateResponse Endauthenticate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/registerRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult Beginregister(GPSWithFriends.Server.registerRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.registerResponse Endregister(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/getLocationRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getLocationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetLocation(GPSWithFriends.Server.getLocationRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.getLocationResponse EndgetLocation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/getMembersRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getMembersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetMembers(GPSWithFriends.Server.getMembersRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.getMembersResponse EndgetMembers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/createGroupRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/createGroupResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegincreateGroup(GPSWithFriends.Server.createGroupRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.createGroupResponse EndcreateGroup(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/setLocationRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/setLocationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginsetLocation(GPSWithFriends.Server.setLocationRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.setLocationResponse EndsetLocation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/getGroupsRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/getGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetGroups(GPSWithFriends.Server.getGroupsRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.getGroupsResponse EndgetGroups(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/removeMemberRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/removeMemberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginremoveMember(GPSWithFriends.Server.removeMemberRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.removeMemberResponse EndremoveMember(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cs.uoregon.edu/GPSwfriends/addMemberRequest", ReplyAction="http://cs.uoregon.edu/GPSwfriends/addMemberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginaddMember(GPSWithFriends.Server.addMemberRequest request, System.AsyncCallback callback, object asyncState);
        
        GPSWithFriends.Server.addMemberResponse EndaddMember(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class group : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] uidsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] uids {
            get {
                return this.uidsField;
            }
            set {
                this.uidsField = value;
                this.RaisePropertyChanged("uids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cs.uoregon.edu/")]
    public partial class location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long latitudeField;
        
        private long longitudeField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticate", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class authenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public authenticateRequest() {
        }
        
        public authenticateRequest(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class authenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.status @return;
        
        public authenticateResponse() {
        }
        
        public authenticateResponse(GPSWithFriends.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lname;
        
        public registerRequest() {
        }
        
        public registerRequest(string email, string password, string fname, string lname) {
            this.email = email;
            this.password = password;
            this.fname = fname;
            this.lname = lname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.status @return;
        
        public registerResponse() {
        }
        
        public registerResponse(GPSWithFriends.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocation", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        public getLocationRequest() {
        }
        
        public getLocationRequest(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocationResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.location @return;
        
        public getLocationResponse() {
        }
        
        public getLocationResponse(GPSWithFriends.Server.location @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMembers", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gid;
        
        public getMembersRequest() {
        }
        
        public getMembersRequest(string gid) {
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMembersResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GPSWithFriends.Server.user[] @return;
        
        public getMembersResponse() {
        }
        
        public getMembersResponse(GPSWithFriends.Server.user[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGroup", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class createGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("uids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] uids;
        
        public createGroupRequest() {
        }
        
        public createGroupRequest(string[] uids) {
            this.uids = uids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createGroupResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class createGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.status @return;
        
        public createGroupResponse() {
        }
        
        public createGroupResponse(GPSWithFriends.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setLocation", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class setLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long latitude;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long longitude;
        
        public setLocationRequest() {
        }
        
        public setLocationRequest(string uid, long latitude, long longitude) {
            this.uid = uid;
            this.latitude = latitude;
            this.longitude = longitude;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setLocationResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class setLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.status @return;
        
        public setLocationResponse() {
        }
        
        public setLocationResponse(GPSWithFriends.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroups", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        public getGroupsRequest() {
        }
        
        public getGroupsRequest(string uid) {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupsResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class getGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public GPSWithFriends.Server.group[] @return;
        
        public getGroupsResponse() {
        }
        
        public getGroupsResponse(GPSWithFriends.Server.group[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeMember", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class removeMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gid;
        
        public removeMemberRequest() {
        }
        
        public removeMemberRequest(string uid, string gid) {
            this.uid = uid;
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeMemberResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class removeMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.status @return;
        
        public removeMemberResponse() {
        }
        
        public removeMemberResponse(GPSWithFriends.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMember", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class addMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gid;
        
        public addMemberRequest() {
        }
        
        public addMemberRequest(string uid, string gid) {
            this.uid = uid;
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMemberResponse", WrapperNamespace="http://cs.uoregon.edu/", IsWrapped=true)]
    public partial class addMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cs.uoregon.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GPSWithFriends.Server.status @return;
        
        public addMemberResponse() {
        }
        
        public addMemberResponse(GPSWithFriends.Server.status @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GPSwfriendsChannel : GPSWithFriends.Server.GPSwfriends, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.status Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.status)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class registerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public registerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.status Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.status)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.location Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.location)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.user[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.user[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.status Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.status)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class setLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public setLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.status Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.status)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.group[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.group[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class removeMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public removeMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.status Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.status)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public GPSWithFriends.Server.status Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((GPSWithFriends.Server.status)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPSwfriendsClient : System.ServiceModel.ClientBase<GPSWithFriends.Server.GPSwfriends>, GPSWithFriends.Server.GPSwfriends {
        
        private BeginOperationDelegate onBeginauthenticateDelegate;
        
        private EndOperationDelegate onEndauthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onauthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginregisterDelegate;
        
        private EndOperationDelegate onEndregisterDelegate;
        
        private System.Threading.SendOrPostCallback onregisterCompletedDelegate;
        
        private BeginOperationDelegate onBegingetLocationDelegate;
        
        private EndOperationDelegate onEndgetLocationDelegate;
        
        private System.Threading.SendOrPostCallback ongetLocationCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMembersDelegate;
        
        private EndOperationDelegate onEndgetMembersDelegate;
        
        private System.Threading.SendOrPostCallback ongetMembersCompletedDelegate;
        
        private BeginOperationDelegate onBegincreateGroupDelegate;
        
        private EndOperationDelegate onEndcreateGroupDelegate;
        
        private System.Threading.SendOrPostCallback oncreateGroupCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetLocationDelegate;
        
        private EndOperationDelegate onEndsetLocationDelegate;
        
        private System.Threading.SendOrPostCallback onsetLocationCompletedDelegate;
        
        private BeginOperationDelegate onBegingetGroupsDelegate;
        
        private EndOperationDelegate onEndgetGroupsDelegate;
        
        private System.Threading.SendOrPostCallback ongetGroupsCompletedDelegate;
        
        private BeginOperationDelegate onBeginremoveMemberDelegate;
        
        private EndOperationDelegate onEndremoveMemberDelegate;
        
        private System.Threading.SendOrPostCallback onremoveMemberCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddMemberDelegate;
        
        private EndOperationDelegate onEndaddMemberDelegate;
        
        private System.Threading.SendOrPostCallback onaddMemberCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GPSwfriendsClient() {
        }
        
        public GPSwfriendsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPSwfriendsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPSwfriendsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPSwfriendsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<authenticateCompletedEventArgs> authenticateCompleted;
        
        public event System.EventHandler<registerCompletedEventArgs> registerCompleted;
        
        public event System.EventHandler<getLocationCompletedEventArgs> getLocationCompleted;
        
        public event System.EventHandler<getMembersCompletedEventArgs> getMembersCompleted;
        
        public event System.EventHandler<createGroupCompletedEventArgs> createGroupCompleted;
        
        public event System.EventHandler<setLocationCompletedEventArgs> setLocationCompleted;
        
        public event System.EventHandler<getGroupsCompletedEventArgs> getGroupsCompleted;
        
        public event System.EventHandler<removeMemberCompletedEventArgs> removeMemberCompleted;
        
        public event System.EventHandler<addMemberCompletedEventArgs> addMemberCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.Beginauthenticate(GPSWithFriends.Server.authenticateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginauthenticate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginauthenticate(string email, string password, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.authenticateRequest inValue = new GPSWithFriends.Server.authenticateRequest();
            inValue.email = email;
            inValue.password = password;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).Beginauthenticate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.authenticateResponse GPSWithFriends.Server.GPSwfriends.Endauthenticate(System.IAsyncResult result) {
            return base.Channel.Endauthenticate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.status Endauthenticate(System.IAsyncResult result) {
            GPSWithFriends.Server.authenticateResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).Endauthenticate(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginauthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.Beginauthenticate(email, password, callback, asyncState);
        }
        
        private object[] OnEndauthenticate(System.IAsyncResult result) {
            GPSWithFriends.Server.status retVal = this.Endauthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnauthenticateCompleted(object state) {
            if ((this.authenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.authenticateCompleted(this, new authenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void authenticateAsync(string email, string password) {
            this.authenticateAsync(email, password, null);
        }
        
        public void authenticateAsync(string email, string password, object userState) {
            if ((this.onBeginauthenticateDelegate == null)) {
                this.onBeginauthenticateDelegate = new BeginOperationDelegate(this.OnBeginauthenticate);
            }
            if ((this.onEndauthenticateDelegate == null)) {
                this.onEndauthenticateDelegate = new EndOperationDelegate(this.OnEndauthenticate);
            }
            if ((this.onauthenticateCompletedDelegate == null)) {
                this.onauthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnauthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginauthenticateDelegate, new object[] {
                        email,
                        password}, this.onEndauthenticateDelegate, this.onauthenticateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.Beginregister(GPSWithFriends.Server.registerRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginregister(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginregister(string email, string password, string fname, string lname, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.registerRequest inValue = new GPSWithFriends.Server.registerRequest();
            inValue.email = email;
            inValue.password = password;
            inValue.fname = fname;
            inValue.lname = lname;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).Beginregister(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.registerResponse GPSWithFriends.Server.GPSwfriends.Endregister(System.IAsyncResult result) {
            return base.Channel.Endregister(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.status Endregister(System.IAsyncResult result) {
            GPSWithFriends.Server.registerResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).Endregister(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginregister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            string fname = ((string)(inValues[2]));
            string lname = ((string)(inValues[3]));
            return this.Beginregister(email, password, fname, lname, callback, asyncState);
        }
        
        private object[] OnEndregister(System.IAsyncResult result) {
            GPSWithFriends.Server.status retVal = this.Endregister(result);
            return new object[] {
                    retVal};
        }
        
        private void OnregisterCompleted(object state) {
            if ((this.registerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.registerCompleted(this, new registerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void registerAsync(string email, string password, string fname, string lname) {
            this.registerAsync(email, password, fname, lname, null);
        }
        
        public void registerAsync(string email, string password, string fname, string lname, object userState) {
            if ((this.onBeginregisterDelegate == null)) {
                this.onBeginregisterDelegate = new BeginOperationDelegate(this.OnBeginregister);
            }
            if ((this.onEndregisterDelegate == null)) {
                this.onEndregisterDelegate = new EndOperationDelegate(this.OnEndregister);
            }
            if ((this.onregisterCompletedDelegate == null)) {
                this.onregisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnregisterCompleted);
            }
            base.InvokeAsync(this.onBeginregisterDelegate, new object[] {
                        email,
                        password,
                        fname,
                        lname}, this.onEndregisterDelegate, this.onregisterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BegingetLocation(GPSWithFriends.Server.getLocationRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetLocation(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetLocation(string uid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.getLocationRequest inValue = new GPSWithFriends.Server.getLocationRequest();
            inValue.uid = uid;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BegingetLocation(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.getLocationResponse GPSWithFriends.Server.GPSwfriends.EndgetLocation(System.IAsyncResult result) {
            return base.Channel.EndgetLocation(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.location EndgetLocation(System.IAsyncResult result) {
            GPSWithFriends.Server.getLocationResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndgetLocation(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetLocation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            return this.BegingetLocation(uid, callback, asyncState);
        }
        
        private object[] OnEndgetLocation(System.IAsyncResult result) {
            GPSWithFriends.Server.location retVal = this.EndgetLocation(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetLocationCompleted(object state) {
            if ((this.getLocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getLocationCompleted(this, new getLocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getLocationAsync(string uid) {
            this.getLocationAsync(uid, null);
        }
        
        public void getLocationAsync(string uid, object userState) {
            if ((this.onBegingetLocationDelegate == null)) {
                this.onBegingetLocationDelegate = new BeginOperationDelegate(this.OnBegingetLocation);
            }
            if ((this.onEndgetLocationDelegate == null)) {
                this.onEndgetLocationDelegate = new EndOperationDelegate(this.OnEndgetLocation);
            }
            if ((this.ongetLocationCompletedDelegate == null)) {
                this.ongetLocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetLocationCompleted);
            }
            base.InvokeAsync(this.onBegingetLocationDelegate, new object[] {
                        uid}, this.onEndgetLocationDelegate, this.ongetLocationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BegingetMembers(GPSWithFriends.Server.getMembersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMembers(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetMembers(string gid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.getMembersRequest inValue = new GPSWithFriends.Server.getMembersRequest();
            inValue.gid = gid;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BegingetMembers(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.getMembersResponse GPSWithFriends.Server.GPSwfriends.EndgetMembers(System.IAsyncResult result) {
            return base.Channel.EndgetMembers(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.user[] EndgetMembers(System.IAsyncResult result) {
            GPSWithFriends.Server.getMembersResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndgetMembers(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetMembers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string gid = ((string)(inValues[0]));
            return this.BegingetMembers(gid, callback, asyncState);
        }
        
        private object[] OnEndgetMembers(System.IAsyncResult result) {
            GPSWithFriends.Server.user[] retVal = this.EndgetMembers(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMembersCompleted(object state) {
            if ((this.getMembersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMembersCompleted(this, new getMembersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMembersAsync(string gid) {
            this.getMembersAsync(gid, null);
        }
        
        public void getMembersAsync(string gid, object userState) {
            if ((this.onBegingetMembersDelegate == null)) {
                this.onBegingetMembersDelegate = new BeginOperationDelegate(this.OnBegingetMembers);
            }
            if ((this.onEndgetMembersDelegate == null)) {
                this.onEndgetMembersDelegate = new EndOperationDelegate(this.OnEndgetMembers);
            }
            if ((this.ongetMembersCompletedDelegate == null)) {
                this.ongetMembersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMembersCompleted);
            }
            base.InvokeAsync(this.onBegingetMembersDelegate, new object[] {
                        gid}, this.onEndgetMembersDelegate, this.ongetMembersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BegincreateGroup(GPSWithFriends.Server.createGroupRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateGroup(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegincreateGroup(string[] uids, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.createGroupRequest inValue = new GPSWithFriends.Server.createGroupRequest();
            inValue.uids = uids;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BegincreateGroup(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.createGroupResponse GPSWithFriends.Server.GPSwfriends.EndcreateGroup(System.IAsyncResult result) {
            return base.Channel.EndcreateGroup(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.status EndcreateGroup(System.IAsyncResult result) {
            GPSWithFriends.Server.createGroupResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndcreateGroup(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegincreateGroup(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string[] uids = ((string[])(inValues[0]));
            return this.BegincreateGroup(uids, callback, asyncState);
        }
        
        private object[] OnEndcreateGroup(System.IAsyncResult result) {
            GPSWithFriends.Server.status retVal = this.EndcreateGroup(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateGroupCompleted(object state) {
            if ((this.createGroupCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createGroupCompleted(this, new createGroupCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createGroupAsync(string[] uids) {
            this.createGroupAsync(uids, null);
        }
        
        public void createGroupAsync(string[] uids, object userState) {
            if ((this.onBegincreateGroupDelegate == null)) {
                this.onBegincreateGroupDelegate = new BeginOperationDelegate(this.OnBegincreateGroup);
            }
            if ((this.onEndcreateGroupDelegate == null)) {
                this.onEndcreateGroupDelegate = new EndOperationDelegate(this.OnEndcreateGroup);
            }
            if ((this.oncreateGroupCompletedDelegate == null)) {
                this.oncreateGroupCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateGroupCompleted);
            }
            base.InvokeAsync(this.onBegincreateGroupDelegate, new object[] {
                        uids}, this.onEndcreateGroupDelegate, this.oncreateGroupCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BeginsetLocation(GPSWithFriends.Server.setLocationRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetLocation(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginsetLocation(string uid, long latitude, long longitude, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.setLocationRequest inValue = new GPSWithFriends.Server.setLocationRequest();
            inValue.uid = uid;
            inValue.latitude = latitude;
            inValue.longitude = longitude;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BeginsetLocation(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.setLocationResponse GPSWithFriends.Server.GPSwfriends.EndsetLocation(System.IAsyncResult result) {
            return base.Channel.EndsetLocation(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.status EndsetLocation(System.IAsyncResult result) {
            GPSWithFriends.Server.setLocationResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndsetLocation(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsetLocation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            long latitude = ((long)(inValues[1]));
            long longitude = ((long)(inValues[2]));
            return this.BeginsetLocation(uid, latitude, longitude, callback, asyncState);
        }
        
        private object[] OnEndsetLocation(System.IAsyncResult result) {
            GPSWithFriends.Server.status retVal = this.EndsetLocation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsetLocationCompleted(object state) {
            if ((this.setLocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setLocationCompleted(this, new setLocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setLocationAsync(string uid, long latitude, long longitude) {
            this.setLocationAsync(uid, latitude, longitude, null);
        }
        
        public void setLocationAsync(string uid, long latitude, long longitude, object userState) {
            if ((this.onBeginsetLocationDelegate == null)) {
                this.onBeginsetLocationDelegate = new BeginOperationDelegate(this.OnBeginsetLocation);
            }
            if ((this.onEndsetLocationDelegate == null)) {
                this.onEndsetLocationDelegate = new EndOperationDelegate(this.OnEndsetLocation);
            }
            if ((this.onsetLocationCompletedDelegate == null)) {
                this.onsetLocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetLocationCompleted);
            }
            base.InvokeAsync(this.onBeginsetLocationDelegate, new object[] {
                        uid,
                        latitude,
                        longitude}, this.onEndsetLocationDelegate, this.onsetLocationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BegingetGroups(GPSWithFriends.Server.getGroupsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetGroups(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetGroups(string uid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.getGroupsRequest inValue = new GPSWithFriends.Server.getGroupsRequest();
            inValue.uid = uid;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BegingetGroups(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.getGroupsResponse GPSWithFriends.Server.GPSwfriends.EndgetGroups(System.IAsyncResult result) {
            return base.Channel.EndgetGroups(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.group[] EndgetGroups(System.IAsyncResult result) {
            GPSWithFriends.Server.getGroupsResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndgetGroups(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetGroups(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            return this.BegingetGroups(uid, callback, asyncState);
        }
        
        private object[] OnEndgetGroups(System.IAsyncResult result) {
            GPSWithFriends.Server.group[] retVal = this.EndgetGroups(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetGroupsCompleted(object state) {
            if ((this.getGroupsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getGroupsCompleted(this, new getGroupsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getGroupsAsync(string uid) {
            this.getGroupsAsync(uid, null);
        }
        
        public void getGroupsAsync(string uid, object userState) {
            if ((this.onBegingetGroupsDelegate == null)) {
                this.onBegingetGroupsDelegate = new BeginOperationDelegate(this.OnBegingetGroups);
            }
            if ((this.onEndgetGroupsDelegate == null)) {
                this.onEndgetGroupsDelegate = new EndOperationDelegate(this.OnEndgetGroups);
            }
            if ((this.ongetGroupsCompletedDelegate == null)) {
                this.ongetGroupsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetGroupsCompleted);
            }
            base.InvokeAsync(this.onBegingetGroupsDelegate, new object[] {
                        uid}, this.onEndgetGroupsDelegate, this.ongetGroupsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BeginremoveMember(GPSWithFriends.Server.removeMemberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginremoveMember(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginremoveMember(string uid, string gid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.removeMemberRequest inValue = new GPSWithFriends.Server.removeMemberRequest();
            inValue.uid = uid;
            inValue.gid = gid;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BeginremoveMember(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.removeMemberResponse GPSWithFriends.Server.GPSwfriends.EndremoveMember(System.IAsyncResult result) {
            return base.Channel.EndremoveMember(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.status EndremoveMember(System.IAsyncResult result) {
            GPSWithFriends.Server.removeMemberResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndremoveMember(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginremoveMember(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            string gid = ((string)(inValues[1]));
            return this.BeginremoveMember(uid, gid, callback, asyncState);
        }
        
        private object[] OnEndremoveMember(System.IAsyncResult result) {
            GPSWithFriends.Server.status retVal = this.EndremoveMember(result);
            return new object[] {
                    retVal};
        }
        
        private void OnremoveMemberCompleted(object state) {
            if ((this.removeMemberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.removeMemberCompleted(this, new removeMemberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void removeMemberAsync(string uid, string gid) {
            this.removeMemberAsync(uid, gid, null);
        }
        
        public void removeMemberAsync(string uid, string gid, object userState) {
            if ((this.onBeginremoveMemberDelegate == null)) {
                this.onBeginremoveMemberDelegate = new BeginOperationDelegate(this.OnBeginremoveMember);
            }
            if ((this.onEndremoveMemberDelegate == null)) {
                this.onEndremoveMemberDelegate = new EndOperationDelegate(this.OnEndremoveMember);
            }
            if ((this.onremoveMemberCompletedDelegate == null)) {
                this.onremoveMemberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnremoveMemberCompleted);
            }
            base.InvokeAsync(this.onBeginremoveMemberDelegate, new object[] {
                        uid,
                        gid}, this.onEndremoveMemberDelegate, this.onremoveMemberCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult GPSWithFriends.Server.GPSwfriends.BeginaddMember(GPSWithFriends.Server.addMemberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddMember(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginaddMember(string uid, string gid, System.AsyncCallback callback, object asyncState) {
            GPSWithFriends.Server.addMemberRequest inValue = new GPSWithFriends.Server.addMemberRequest();
            inValue.uid = uid;
            inValue.gid = gid;
            return ((GPSWithFriends.Server.GPSwfriends)(this)).BeginaddMember(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GPSWithFriends.Server.addMemberResponse GPSWithFriends.Server.GPSwfriends.EndaddMember(System.IAsyncResult result) {
            return base.Channel.EndaddMember(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private GPSWithFriends.Server.status EndaddMember(System.IAsyncResult result) {
            GPSWithFriends.Server.addMemberResponse retVal = ((GPSWithFriends.Server.GPSwfriends)(this)).EndaddMember(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginaddMember(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uid = ((string)(inValues[0]));
            string gid = ((string)(inValues[1]));
            return this.BeginaddMember(uid, gid, callback, asyncState);
        }
        
        private object[] OnEndaddMember(System.IAsyncResult result) {
            GPSWithFriends.Server.status retVal = this.EndaddMember(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddMemberCompleted(object state) {
            if ((this.addMemberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addMemberCompleted(this, new addMemberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addMemberAsync(string uid, string gid) {
            this.addMemberAsync(uid, gid, null);
        }
        
        public void addMemberAsync(string uid, string gid, object userState) {
            if ((this.onBeginaddMemberDelegate == null)) {
                this.onBeginaddMemberDelegate = new BeginOperationDelegate(this.OnBeginaddMember);
            }
            if ((this.onEndaddMemberDelegate == null)) {
                this.onEndaddMemberDelegate = new EndOperationDelegate(this.OnEndaddMember);
            }
            if ((this.onaddMemberCompletedDelegate == null)) {
                this.onaddMemberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddMemberCompleted);
            }
            base.InvokeAsync(this.onBeginaddMemberDelegate, new object[] {
                        uid,
                        gid}, this.onEndaddMemberDelegate, this.onaddMemberCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override GPSWithFriends.Server.GPSwfriends CreateChannel() {
            return new GPSwfriendsClientChannel(this);
        }
        
        private class GPSwfriendsClientChannel : ChannelBase<GPSWithFriends.Server.GPSwfriends>, GPSWithFriends.Server.GPSwfriends {
            
            public GPSwfriendsClientChannel(System.ServiceModel.ClientBase<GPSWithFriends.Server.GPSwfriends> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult Beginauthenticate(GPSWithFriends.Server.authenticateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("authenticate", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.authenticateResponse Endauthenticate(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.authenticateResponse _result = ((GPSWithFriends.Server.authenticateResponse)(base.EndInvoke("authenticate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginregister(GPSWithFriends.Server.registerRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("register", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.registerResponse Endregister(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.registerResponse _result = ((GPSWithFriends.Server.registerResponse)(base.EndInvoke("register", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetLocation(GPSWithFriends.Server.getLocationRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getLocation", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.getLocationResponse EndgetLocation(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.getLocationResponse _result = ((GPSWithFriends.Server.getLocationResponse)(base.EndInvoke("getLocation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetMembers(GPSWithFriends.Server.getMembersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getMembers", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.getMembersResponse EndgetMembers(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.getMembersResponse _result = ((GPSWithFriends.Server.getMembersResponse)(base.EndInvoke("getMembers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegincreateGroup(GPSWithFriends.Server.createGroupRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("createGroup", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.createGroupResponse EndcreateGroup(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.createGroupResponse _result = ((GPSWithFriends.Server.createGroupResponse)(base.EndInvoke("createGroup", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsetLocation(GPSWithFriends.Server.setLocationRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("setLocation", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.setLocationResponse EndsetLocation(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.setLocationResponse _result = ((GPSWithFriends.Server.setLocationResponse)(base.EndInvoke("setLocation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetGroups(GPSWithFriends.Server.getGroupsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getGroups", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.getGroupsResponse EndgetGroups(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.getGroupsResponse _result = ((GPSWithFriends.Server.getGroupsResponse)(base.EndInvoke("getGroups", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginremoveMember(GPSWithFriends.Server.removeMemberRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("removeMember", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.removeMemberResponse EndremoveMember(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.removeMemberResponse _result = ((GPSWithFriends.Server.removeMemberResponse)(base.EndInvoke("removeMember", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddMember(GPSWithFriends.Server.addMemberRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("addMember", _args, callback, asyncState);
                return _result;
            }
            
            public GPSWithFriends.Server.addMemberResponse EndaddMember(System.IAsyncResult result) {
                object[] _args = new object[0];
                GPSWithFriends.Server.addMemberResponse _result = ((GPSWithFriends.Server.addMemberResponse)(base.EndInvoke("addMember", _args, result)));
                return _result;
            }
        }
    }
}
